DROP DATABASE IF EXISTS daem_db;
CREATE DATABASE daem_db;
USE daem_db;



DROP TABLE IF EXISTS `REGION`;

CREATE TABLE `REGION` (
  `ID_REGION` int(11) NOT NULL AUTO_INCREMENT,
  `nombreRegion` varchar(15) NOT NULL,
  `numeroRegion` int(11) NOT NULL,
  `comunaRegion` varchar(20) NOT NULL,
  PRIMARY KEY (`ID_REGION`)
  );


DROP TABLE IF EXISTS `CIUDAD`;

CREATE TABLE `CIUDAD` (
  `ID_CIUDAD` int(11) NOT NULL AUTO_INCREMENT,
  `nombreCiudad` varchar(20)  DEFAULT'' NOT NULL,
  `localidadCiudad` varchar(20) DEFAULT NOT NULL,
  PRIMARY KEY (`ID_CIUDAD`)
  );

DROP TABLE IF EXISTS `CALLE`;
CREATE TABLE `CALLE` (
  `ID_CALLE` int(11) NOT NULL AUTO_INCREMENT,
  `nombreCalle` varchar(20)  NOT NULL,
  `numeroCalle` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_CALLE`)
  );

DROP TABLE IF EXISTS `LECTOR`;

CREATE TABLE `LECTOR` (
  `ID_LECTOR` int(11) NOT NULL AUTO_INCREMENT,
  `nombreLector` varchar(20) DEFAULT'' NOT NULL,
  PRIMARY KEY (`ID_LECTOR`)
  );





DROP TABLE IF EXISTS `USUARIO`;

CREATE TABLE `USUARIO` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `administrador` bit(1) DEFAULT'' NULL,
  `nombreUsuario` varchar(20)  DEFAULT'' NULL,
  `apellidoPaternoUsuario` varchar(20)  DEFAULT'' NULL,
  `apellidoMaternoUsuario` varchar(20)  DEFAULT'' NULL,
  `usuarioUsuario` varchar(20)  DEFAULT'' NULL,
  `passwordUsuario` varchar(20)  DEFAULT'' NULL,
  `fechaModificacionUsuario` datetime DEFAULT NULL,
  `ocupacionUsuario` varchar(15) DEFAULT'' NULL;
  `FK_USUARIO_ID_REGION_REGION` int,
  `FK_USUARIO_ID_CIUDAD_CIUDAD` int,
  `FK_USUARIO_ID_CALLE_CALLE` int,
  PRIMARY KEY (`ID_USUARIO`),
  CONSTRAINT `FK_USUARIO_ID_REGION_REGION` FOREIGN KEY (`FK_USUARIO_ID_REGION_REGION`) REFERENCES `REGION` (`ID_REGION`),
  CONSTRAINT `FK_USUARIO_ID_CIUDAD_CIUDAD` FOREIGN KEY (`FK_USUARIO_ID_CIUDAD_CIUDAD`) REFERENCES `CIUDAD` (`ID_CIUDAD`),
  CONSTRAINT `FK_USUARIO_ID_CALLE_CALLE` FOREIGN KEY (`FK_USUARIO_ID_CALLE_CALLE`) REFERENCES `CALLE` (`ID_CALLE`)
  );

DROP TABLE IF EXISTS `NOTICIA`;
CREATE TABLE `NOTICIA` (
  `ID_NOTICIA` int(11) NOT NULL AUTO_INCREMENT,
  `referenciaImagenNoticia` varchar(10) DEFAULT'' NULL,
  `fechaNoticia` date NOT NULL,
  `secionNoticia` varchar(20) DEFAULT'' NULL,
  `noticiaNoticia` text NOT NULL,
  `tituloNoticia` text  NOT NULL,
  `FK_NOTICIA_ID_USUARIO_USUARIO` int,
  PRIMARY KEY (`ID_NOTICIA`),
  CONSTRAINT `FK_NOTICIA_ID_USUARIO_USUARIO` FOREIGN KEY (`FK_NOTICIA_ID_USUARIO_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`)
  );


DROP TABLE IF EXISTS `COMENTARIO`;

CREATE TABLE `COMENTARIO` (
  `ID_COMENTARIO` int(11) NOT NULL AUTO_INCREMENT,
  `fechaComentario` datetime DEFAULT NULL,
  `comentarioComentario` text ,
  `FK_COMENTARIO_ID_LECTOR_LECTOR` int,
  `FK_COMENTARIO_ID_NOTICIA_NOTICIA` int,
  PRIMARY KEY (`ID_COMENTARIO`),
  CONSTRAINT `FK_COMENTARIO_ID_LECTOR_LECTOR` FOREIGN KEY (`FK_COMENTARIO_ID_LECTOR_LECTOR`) REFERENCES `LECTOR` (`ID_LECTOR`),
  CONSTRAINT `FK_COMENTARIO_ID_NOTICIA_NOTICIA` FOREIGN KEY (`FK_COMENTARIO_ID_NOTICIA_NOTICIA`) REFERENCES `NOTICIA` (`ID_NOTICIA`)
  );




DROP TABLE IF EXISTS `CONTACTO`;

CREATE TABLE `CONTACTO` (
  `ID_CONTACTO` int(11) NOT NULL AUTO_INCREMENT,
  `telefonoContacto` int(11) DEFAULT'' NOT NULL,
  `correoContacto` varchar(20) DEFAULT'' NULL,
  PRIMARY KEY (`ID_CONTACTO`),
  CONSTRAINT `FK_CONTACTO_ID_USUARIO_USUARIO` FOREIGN KEY (`FK_CONTACTO_ID_USUARIO_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`),
  CONSTRAINT `FK_CONTACTO_ID_LECTOR_LECTOR` FOREIGN KEY (`FK_CONTACTO_ID_LECTOR_LECTOR`) REFERENCES `LECTOR` (`ID_LECTOR`)
  );




  DROP TABLE IF EXISTS `ESCUELA`;

  CREATE TABLE `ESCUELA` (
    `ID_ESCUELA` int(11) NOT NULL AUTO_INCREMENT,
    `nombreEscuela` varchar(15) DEFAULT NULL,
    `codigoEscuela` varchar(15) DEFAULT NULL,
    `FK_ESCUELA_ID_CALLE_CALLE` int,
    `FK_ESCUELA_ID_CIUDAD_CIUDAD` int,
    `FK_ESCUELA_ID_REGION_REGION` int,
    PRIMARY KEY (`ID_ESCUELA`),
    CONSTRAINT `FK_ESCUELA_ID_CALLE_CALLE` FOREIGN KEY (`FK_ESCUELA_ID_CALLE_CALLE`) REFERENCES `CALLE` (`ID_CALLE`),
    CONSTRAINT `FK_ESCUELA_ID_CIUDAD_CIUDAD` FOREIGN KEY (`FK_ESCUELA_ID_CIUDAD_CIUDAD`) REFERENCES `CIUDAD` (`ID_CIUDAD`),
    CONSTRAINT `FK_ESCUELA_ID_REGION_REGION` FOREIGN KEY (`FK_ESCUELA_ID_REGION_REGION`) REFERENCES `REGION` (`ID_REGION`)
    );
