DROP DATABASE IF EXISTS daem_db;
CREATE DATABASE daem_db;
USE daem_db;



DROP TABLE IF EXISTS `REGION`;

CREATE TABLE `REGION` (
  `ID_REGION` int(11) NOT NULL AUTO_INCREMENT,
  `nombreRegion` varchar(15) NOT NULL,
  `numeroRegion` int(11) NOT NULL,
  `comunaRegion` varchar(20) NOT NULL,
  PRIMARY KEY (`ID_REGION`)
  );


DROP TABLE IF EXISTS `CIUDAD`;
CREATE TABLE `CIUDAD` (
  `ID_CIUDAD` int(11) NOT NULL AUTO_INCREMENT,
  `nombreCiudad` varchar(20)  DEFAULT NOT NULL,
  `localidadCiudad` varchar(20) DEFAULT NOT NULL,
  PRIMARY KEY (`ID_CIUDAD`)
  );

DROP TABLE IF EXISTS `CALLE`;
CREATE TABLE `CALLE` (
  `ID_CALLE` int(11) NOT NULL AUTO_INCREMENT,
  `nombreCalle` varchar(20)  NOT NULL,
  `numeroCalle` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_CALLE`)
  );

DROP TABLE IF EXISTS `USUARIO`;

CREATE TABLE `USUARIO` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `administrador` bit(1) DEFAULT NULL,
  `nombreUsuario` varchar(20)  DEFAULT NULL,
  `apellidoPaternoUsuario` varchar(20)  DEFAULT NULL,
  `apellidoMaternoUsuario` varchar(20)  DEFAULT NULL,
  `usuarioUsuario` varchar(20)  DEFAULT NULL,
  `passwordUsuario` varchar(20)  DEFAULT NULL,
  `fechaModificacionUsuario` datetime DEFAULT NULL,
  `REGION_ID_REGION` int(11) NOT NULL,
  `CIUDAD_ID_CIUDAD` int(11) NOT NULL,
  `CALLE_ID_CALLE` int(11) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  `FK_USUARIO_ID_REGION` int,
  `FK_USUARIO_ID_CIUDAD` int,
  `FK_USUARIO_ID_CALLE` int,
  CONSTRAINT `FK_USUARIO_ID_REGION` FOREIGN KEY (`FK_USUARIO_ID_REGION`) REFERENCES `REGION` (`ID_REGION`),
  CONSTRAINT `FK_USUARIO_ID_CIUDAD` FOREIGN KEY (`FK_USUARIO_ID_CIUDAD`) REFERENCES `CIUDAD` (`ID_CIUDAD`),
  CONSTRAINT `FK_USUARIO_ID_CALLE` FOREIGN KEY (`FK_USUARIO_ID_CALLE`) REFERENCES `CALLE` (`ID_CALLE`)
  );

DROP TABLE IF EXISTS `NOTICIA`;
CREATE TABLE `NOTICIA` (
  `ID_NOTICIA` int(11) NOT NULL AUTO_INCREMENT,
  `referenciaImagenNoticia` varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  `fechaNoticia` date NOT NULL,
  `secionNoticia` varchar(20) COLLATE latin1_spanish_ci DEFAULT NULL,
  `noticiaNoticia` text COLLATE latin1_spanish_ci NOT NULL,
  `tituloNoticia` text COLLATE latin1_spanish_ci NOT NULL,
  `USUARIO_ID_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_NOTICIA`),
  KEY `fk_NOTICIA_USUARIO1_idx` (`USUARIO_ID_USUARIO`),
  CONSTRAINT `fk_NOTICIA_USUARIO1` FOREIGN KEY (`USUARIO_ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ); 
DROP TABLE IF EXISTS `LECTOR`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `LECTOR` (
  `ID_LECTOR` int(11) NOT NULL AUTO_INCREMENT,
  `nombreLector` varchar(20) COLLATE latin1_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`ID_LECTOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `CONTACTO`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `CONTACTO` (
  `ID_CONTACTO` int(11) NOT NULL AUTO_INCREMENT,
  `telefonoContacto` int(11) DEFAULT NULL,
  `correoContacto` varchar(20) COLLATE latin1_spanish_ci DEFAULT NULL,
  `USUARIO_ID_USUARIO` int(11) NOT NULL,
  `LECTOR_ID_LECTOR` int(11) NOT NULL,
  PRIMARY KEY (`ID_CONTACTO`),
  KEY `fk_CONTACTO_USUARIO1_idx` (`USUARIO_ID_USUARIO`),
  KEY `fk_CONTACTO_LECTOR1_idx` (`LECTOR_ID_LECTOR`),
  CONSTRAINT `fk_CONTACTO_USUARIO1` FOREIGN KEY (`USUARIO_ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTACTO_LECTOR1` FOREIGN KEY (`LECTOR_ID_LECTOR`) REFERENCES `LECTOR` (`ID_LECTOR`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `COMENTARIO`;
CREATE TABLE `COMENTARIO` (
  `ID_COMENTARIO` int(11) NOT NULL AUTO_INCREMENT,
  `fechaComentario` datetime DEFAULT NULL,
  `LECTOR_ID_LECTOR` int(11) NOT NULL,
  `NOTICIA_ID_NOTICIA` int(11) NOT NULL,
  `comentarioComentario` text COLLATE latin1_spanish_ci,
  PRIMARY KEY (`ID_COMENTARIO`),
  `fk_COMENTARIO_LECTOR_idx` int,
  `fk_COMENTARIO_NOTICIA1_idx` int,
  CONSTRAINT `fk_COMENTARIO_LECTOR` FOREIGN KEY (`LECTOR_ID_LECTOR`) REFERENCES `LECTOR` (`ID_LECTOR`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_NOTICIA1` FOREIGN KEY (`NOTICIA_ID_NOTICIA`) REFERENCES `NOTICIA` (`ID_NOTICIA`) ON DELETE NO ACTION ON UPDATE NO ACTION
  );
